In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("supply_chain_train.csv")

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8101 entries, 0 to 8100
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   train_idx                 8101 non-null   int64  
 1   CLIENTNUM                 8101 non-null   int64  
 2   Customer_Age              8101 non-null   int64  
 3   Gender                    8101 non-null   object 
 4   Dependent_count           8101 non-null   int64  
 5   Education_Level           8101 non-null   object 
 6   Marital_Status            8101 non-null   object 
 7   Income_Category           8101 non-null   object 
 8   Card_Category             8101 non-null   object 
 9   Months_on_book            8101 non-null   int64  
 10  Total_Relationship_Count  8101 non-null   int64  
 11  Months_Inactive_12_mon    8101 non-null   int64  
 12  Contacts_Count_12_mon     8101 non-null   int64  
 13  Credit_Limit              8101 non-null   float64
 14  Total_Re

In [9]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,:-1].values

In [10]:
x

array([[0, 713071383, 54, ..., 99, 0.678, 0.464],
       [1, 714246333, 58, ..., 39, 0.393, 0.334],
       [2, 718206783, 45, ..., 36, 1.25, 0.103],
       ...,
       [8098, 714140133, 42, ..., 74, 1.0, 0.669],
       [8099, 720244983, 40, ..., 42, 0.312, 0.479],
       [8100, 827123883, 53, ..., 92, 0.614, 0.0]], dtype=object)

In [11]:
y

array([[0, 713071383, 54, ..., 99, 0.678, 0.464],
       [1, 714246333, 58, ..., 39, 0.393, 0.334],
       [2, 718206783, 45, ..., 36, 1.25, 0.103],
       ...,
       [8098, 714140133, 42, ..., 74, 1.0, 0.669],
       [8099, 720244983, 40, ..., 42, 0.312, 0.479],
       [8100, 827123883, 53, ..., 92, 0.614, 0.0]], dtype=object)

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [54]:
from sklearn.metrics import accuracy_score , classification_report

In [43]:
dataset

train_idx  CLIENTNUM  Customer_Age Gender  Dependent_count  \
0             0  713071383            54      F                1   
1             1  714246333            58      F                4   
2             2  718206783            45      F                4   
3             3  721096983            34      F                2   
4             4  720028683            49      F                2   
...         ...        ...           ...    ...              ...   
8096       8096  769053033            44      F                1   
8097       8097  714406158            53      F                3   
8098       8098  714140133            42      F                4   
8099       8099  720244983            40      M                3   
8100       8100  827123883            53      M                4   

     Education_Level Marital_Status Income_Category Card_Category  \
0            Unknown         Single         Unknown          Blue   
1        High School        Married         Unknown          Blue   
2            Unknown         Single  Less than $40K          Gold   
3           Graduate         Single  Less than $40K          Blue   
4        High School        Married     $40K - $60K          Blue   
...              ...            ...             ...           ...   
8096        Graduate         Single     $40K - $60K          Blue   
8097     High School       Divorced         Unknown          Blue   
8098        Graduate        Unknown  Less than $40K          Blue   
8099         Unknown         Single     $40K - $60K          Blue   
8100     High School         Single     $60K - $80K          Blue   

      Months_on_book  ...  Contacts_Count_12_mon  Credit_Limit  \
0                 36  ...                      3        3723.0   
1                 48  ...                      3        5396.0   
2                 36  ...                      3       15987.0   
3                 36  ...                      4        3625.0   
4                 39  ...                      4        2720.0   
...              ...  ...                    ...           ...   
8096              38  ...                      5        4142.0   
8097              36  ...                      6        7939.0   
8098              32  ...                      2        2314.0   
8099              28  ...                      1        3563.0   
8100              49  ...                      2        3858.0   

      Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0                    1728           1995.0                 0.595   
1                    1803           3593.0                 0.493   
2                    1648          14339.0                 0.732   
3                    2517           1108.0                 1.158   
4                    1926            794.0                 0.602   
...                   ...              ...                   ...   
8096                 2517           1625.0                 0.809   
8097                    0           7939.0                 0.551   
8098                 1547            767.0                 0.804   
8099                 1707           1856.0                 0.506   
8100                    0           3858.0                 0.670   

      Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                8554              99                0.678   
1                2107              39                0.393   
2                1436              36                1.250   
3                2616              46                1.300   
4                3806              61                0.794   
...               ...             ...                  ...   
8096             2104              44                0.833   
8097             2269              42                0.312   
8098             4678              74                1.000   
8099             1482              42                0.312   
8100             4472              92                0.614   

     

In [44]:
x = dataset[['CLIENTNUM','Customer_Age','Credit_Limit','Total_Revolving_Bal', 'Total_Trans_Amt', 'Total_Trans_Ct']]

In [45]:
y = dataset[['Attrition_Flag']]

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.7, random_state=80)

In [47]:
Rf = RandomForestClassifier(n_estimators=200, random_state=80)

In [48]:
Rf.fit(x_train , y_train)

C:\Users\kanik\AppData\Local\Temp\ipykernel_22036\56334316.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  Rf.fit(x_train , y_train)


RandomForestClassifier(n_estimators=200, random_state=80)

In [56]:
predict = Rf.predict(x_test)
predict

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [57]:
accuracy = accuracy_score(y_test, predict)
accuracy

0.9315817316169988

In [59]:
result = classification_report(y_test, predict)
result

'              precision    recall  f1-score   support\n\n           0       0.82      0.72      0.77       892\n           1       0.95      0.97      0.96      4779\n\n    accuracy                           0.93      5671\n   macro avg       0.89      0.84      0.86      5671\nweighted avg       0.93      0.93      0.93      5671\n'